---
antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Introduction"
      solveButton: false
    - name: module-01
      label: "create-network-backup-job"
      solveButton: true
    - name: module-02
      label: "backup-job"
      solveButton: true
    - name: module-03
      label: "restore-network-automation"
      solveButton: true

tabs:
  - name: ">_Controller-Terminal"
    url: /wetty_controller

